---
- name: Software Installation Playbook
  hosts: testing
  gather_facts: false
  become: true

  tasks:
    - name: Check for existing apt processes
      shell: |
        if pgrep -x "apt|apt-get"; then
          sudo pkill -9 "apt|apt-get"
          sudo rm -f /var/lib/apt/lists/lock
        fi
      args:
        executable: /bin/bash
      ignore_errors: true
      changed_when: false

    - name: Update package cache
      shell: |
        sudo apt-get clean
        sudo apt-get update -qq
      args:
        executable: /bin/bash
        # timeout: 30

    - name: Install Python via dpkg
      shell: |
        apt-get install -y --no-install-recommends python3-minimal
      args:
        executable: /bin/bash

    - name: Ensure `pip` is upgraded to the latest version
      pip:
        name: pip
        state: latest
        executable: /usr/bin/pip3

    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      become: true
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
        state: present

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker.io
          - containerd
        state: present
        update_cache: no 

    - name: Kubectl Download
      shell: |
        curl -L --retry 3 --output /usr/local/bin/kubectl https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
        chmod +x /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Download Kustomize
      shell: |
        curl -L --retry 3 --output /tmp/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz
      args:
        creates: /tmp/kustomize.tar.gz

    - name: Install Kustomize
      unarchive:
        src: /tmp/kustomize.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Install OpenJDK 21 (LTS)
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Verify installations
      shell: "docker --version && kubectl version --client && kustomize version && docker-compose --version && java --version && python3 --version"
      register: verification_output

    - name: Display verification output
      debug:
        msg: "{{ verification_output.stdout_lines }}"