---
- name: Software Installation Playbook
  hosts: test
  gather_facts: true
  become: true

  tasks:
    - name: Clear any existing APT locks
      shell: |
        sudo rm -f /var/lib/apt/lists/lock \
                   /var/lib/dpkg/lock \
                   /var/lib/dpkg/lock-frontend
      args:
        warn: false
      ignore_errors: true
      register: apt_lock_cleanup
      changed_when: "'No such file' not in apt_lock_cleanup.stderr"

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    - name: Ensure required Python packages are installed
      pip:
        name:
          - requests
          - urllib3
        state: latest
        executable: /usr/bin/pip3

    - name: Add Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker.io
          - containerd
        state: present
        update_cache: no 

    - name: Kubectl Download
      shell: |
        curl -L --retry 3 --output /usr/local/bin/kubectl https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
        chmod +x /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Download Kustomize
      shell: |
        curl -L --retry 3 --output /tmp/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz
      args:
        creates: /tmp/kustomize.tar.gz

    - name: Install Kustomize
      unarchive:
        src: /tmp/kustomize.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Install OpenJDK 21 (LTS)
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Verify installations
      shell: "docker --version && kubectl version --client && kustomize version && docker-compose --version && java --version && python3 --version"
      register: verification_output

    - name: Display verification output
      debug:
        msg: "{{ verification_output.stdout_lines }}"