---
- name: Software Installation Playbook
  hosts: testing
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Ensure keyring directory exists
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Download Docker installation script
      shell: "curl -fsSL https://get.docker.com -o /tmp/get-docker.sh"

    - name: Verify Docker installation script exists
      stat:
        path: /tmp/get-docker.sh
      register: docker_script

    # - name: Run Docker installation script with verbose output and timeout
    #   block:
    #     - name: Execute Docker installation script
    #       shell: >
    #         bash /tmp/get-docker.sh
    #       args:
    #         executable: /bin/bash
    #       register: docker_install
    #       timeout: 60
    #       changed_when: docker_install.rc == 0

    # - name: Debug Docker installation if failed
    #   block:
    #     - name: Display Docker installation output
    #       debug:
    #         var: docker_install
    #       when: docker_install.rc != 0

    #     - name: Fail if Docker installation unsuccessful
    #       fail:
    #         msg: "Docker installation failed with return code {{ docker_install.rc }}"
    #       when: docker_install.rc != 0

    - name: Run Docker installation script with extended timeout
      block:
        - name: Execute Docker installation script
          shell: |
            chmod +x /tmp/get-docker.sh
            /bin/bash /tmp/get-docker.sh
          args:
            executable: /bin/bash
          async: "{{ docker_install_timeout }}"
          poll: 10 
          register: docker_install_result
          changed_when: docker_install_result.rc == 0

        - name: Check Docker installation result
          fail:
            msg: "Docker installation failed with return code {{ docker_install_result.rc }}"
          when: docker_install_result.rc != 0

      rescue:
        - name: Display Docker installation log
          shell: cat /tmp/get-docker.sh.log || echo "No log file found"
          register: docker_install_log
          changed_when: false

        - name: Show Docker installation log
          debug:
            var: docker_install_log.stdout_lines

        - name: Fail the playbook with detailed message
          fail:
            msg: "Docker installation failed. See log output above for details."

    - name: Add current user to Docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes

    - name: Update apt package index
      apt:
        update_cache: yes

    # - name: Add Docker GPG key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present
    #
    # - name: Add Docker repository
    #   apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    #     state: present

    # - name: Install Docker
    #   apt:
    #     name:
    #       - docker.io
    #       - containerd
    #     state: present
    #     update_cache: no 

    - name: Kubectl Download
      shell: |
        curl -L --retry 3 --output /usr/local/bin/kubectl https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
        chmod +x /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Download Kustomize
      shell: |
        curl -L --retry 3 --output /tmp/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz
      args:
        creates: /tmp/kustomize.tar.gz

    - name: Install Kustomize
      unarchive:
        src: /tmp/kustomize.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Install OpenJDK 21 (LTS)
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Verify installations
      shell: "docker --version && kubectl version --client && kustomize version && docker-compose --version && java --version && python3 --version"
      register: verification_output

    - name: Display verification output
      debug:
        msg: "{{ verification_output.stdout_lines }}"