---
- name: Software Installation Playbook
  hosts: testing
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: Fix APT directory permissions
      file:
        path: /var/lib/apt/
        state: directory
        mode: '0755'
        owner: root
        group: root
        recurse: yes

    - name: Ensure keyring directory exists
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Install prerequisite packages
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
          - software-properties-common
        state: present
        update_cache: yes

    - name: Download Docker installation script
      shell: "curl -fsSL https://get.docker.com -o /tmp/get-docker.sh"

    # - name: Run Docker installation script
    #   shell: "sh /tmp/get-docker.sh"

    - name: Run Docker installation script
      command: /bin/sh /tmp/get-docker.sh
      register: docker_install
      retries: 3
      delay: 10
      until: docker_install.rc == 0
      ignore_errors: true

    - name: Add current user to Docker group
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: yes

    - name: Update apt package index
      apt:
        update_cache: yes

    # - name: Add Docker GPG key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present
    #
    # - name: Add Docker repository
    #   apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
    #     state: present

    # - name: Install Docker
    #   apt:
    #     name:
    #       - docker.io
    #       - containerd
    #     state: present
    #     update_cache: no 

    - name: Kubectl Download
      shell: |
        curl -L --retry 3 --output /usr/local/bin/kubectl https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl
        chmod +x /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Download Kustomize
      shell: |
        curl -L --retry 3 --output /tmp/kustomize.tar.gz https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz
      args:
        creates: /tmp/kustomize.tar.gz

    - name: Install Kustomize
      unarchive:
        src: /tmp/kustomize.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        mode: '0755'

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Install OpenJDK 21 (LTS)
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Verify installations
      shell: "docker --version && kubectl version --client && kustomize version && docker-compose --version && java --version && python3 --version"
      register: verification_output

    - name: Display verification output
      debug:
        msg: "{{ verification_output.stdout_lines }}"