---
- name: Software Installation Playbook
  hosts: test
  gather_facts: true
  become: true

  tasks:
    # - name: Add Docker GPG key
    #   shell: |
    #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

    # - name: Add Docker repository
    #   shell: |
    #     echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    # - name: Install Docker CE
    #   apt:
    #     name:
    #       - docker-ce
    #       - docker-ce-cli
    #       - containerd.io
    #     state: present
    #     update_cache: no 

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags:
        - docker
        
    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add Kubernetes GPG key
      shell: |
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/kubernetes-archive-keyring.gpg

    - name: Add Kubernetes repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list > /dev/null

    - name: Install kubectl
      apt:
        name: kubectl
        state: present
        update_cache: yes

    - name: Download Kustomize
      get_url:
        url: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.3.0/kustomize_v5.3.0_linux_amd64.tar.gz"
        dest: "/tmp/kustomize.tar.gz"
        mode: "0755"

    - name: Extract and install Kustomize
      unarchive:
        src: "/tmp/kustomize.tar.gz"
        dest: "/usr/local/bin/"
        remote_src: yes
        mode: "0755"

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose

    - name: Install OpenJDK 21 (LTS)
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install Python and pip
      apt:
        name:
          - python3
          - python3-pip
        state: present

    - name: Verify installations
      shell: "docker --version && kubectl version --client && kustomize version && docker-compose --version && java --version && python3 --version"
      register: verification_output

    - name: Display verification output
      debug:
        msg: "{{ verification_output.stdout_lines }}"