---
- name: Check Software Installation Playbook
  hosts: test
  gather_facts: false

  tasks:
    - name: Check Python 3.13 Installation
      command: python3 --version
      register: python_check
      ignore_errors: true

    - name: Check Docker Installation
      command: docker --version
      register: docker_check
      ignore_errors: true

    - name: Check Docker Compose Installation
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: true

    - name: Check Kubernetes Installation
      command: kubectl --version
      register: kubernetes_check
      ignore_errors: true

    - name: Check Kustomize Installation
      command: kustomize --version
      register: kustomize_check
      ignore_errors: true

    - name: Check Java Presence
      command: java --version
      register: java_check
      ignore_errors: true


    - name: Display Check Results
      debug:
        msg: |
          Python 3.13.2: {{ "INSTALLED" if python_check.rc == 0 else "NOT INSTALLED" }}
          Kustomize: {{ "INSTALLED" if kustomize_check.rc else "NOT INSTALLED" }}
          Docker: {{ "INSTALLED" if docker_check.rc else "NOT INSTALLED" }}
          Kubernetes: {{ "INSTALLED" if kubectl_check.rc else "NOT INSTALLED" }}
          Docker Compose: {{ "INSTALLED" if docker_compose_check.rc else "NOT INSTALLED" }}
          Java: {{ "INSTALLED" if java_check.rc else "NOT INSTALLED" }}
