---
- name: Check Software Installation Playbook
  hosts: test
  gather_facts: false

  tasks:
    - name: Check Python 3.13 Installation
      command: python3 --version
      register: python_check
      ignore_errors: true

    - name: Check Docker Installation
      command: docker --version
      register: docker_check
      ignore_errors: true

    - name: Check Docker Compose Installation
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: true

    - name: Check Kubernetes Installation
      command: kubectl --version
      register: kubernetes_check
      ignore_errors: true

    - name: Check Kustomize Installation
      command: kustomize version
      register: kustomize_check
      ignore_errors: true

    - name: Check Java Presence
      command: java --version
      register: java_check
      ignore_errors: true

    - name: Display Check Results
      debug:
        msg: |
          Python: {{ (python_check.stdout + python_check.stderr) | default("NOT INSTALLED") | replace('\n', '') }}
          Docker: {{ (docker_check.stdout + docker_check.stderr) | default("NOT INSTALLED") | replace('\n', '') }}
          Docker Compose: {{ (docker_compose_check.stdout + docker_compose_check.stderr) | default("NOT INSTALLED") | replace('\n', '') }}
          Kubernetes: {{ (kubernetes_check.stdout + kubernetes_check.stderr) | default("NOT INSTALLED") | replace('\n', '') }}
          Kustomize: {{ (kustomize_check.stdout + kustomize_check.stderr) | default("NOT INSTALLED") | replace('\n', '') }}
          Java: {{ (java_check.stdout + java_check.stderr) | default("NOT INSTALLED") | replace('\n', '') }}
