pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = "False"
        PRIVATE_KEY_PATH = "/var/jenkins_home/.ssh/id_ed25519"
        ANSIBLE_CONFIG = "/var/jenkins_home/ansible/ansible.cfg"
    }

    stages {
        stage('Set SSH Key Permissions') {
            steps {
                script {
                    sh 'chmod 600 /var/jenkins_home/.ssh/id_ed25519'
                }
            }
        }

        stage('Pull JenkinsFile'){
            steps{
                script {
                    sh 'rm -rf infra'
                    git branch: 'main', url: 'https://github.com/FonsahPageo/infra-sandbox.git'
                }
            }
        }

        stage('Export configManagement directory'){
            steps{
                script{
                    sh 'cp -R configManagement/* /var/jenkins_home/ansible'
                }
            }
        }

        stage('Syntax Check') {
            steps {
                script {
                     sh '''
                    ansible-playbook -i /var/jenkins_home/ansible/inventory/hosts.ini \
                    /var/jenkins_home/ansible/playbooks/install_tools.yaml \
                    --syntax-check --diff
                    '''
                }
            }
        }

        stage('Check') {
            steps {
                script {
                    sh '''
                    ansible-playbook -i /var/jenkins_home/ansible/inventory/hosts.ini \
                    /var/jenkins_home/ansible/playbooks/install_tools.yaml --check --diff \
                    --private-key ${PRIVATE_KEY_PATH}
                    '''
                }
            }
        }

        stage('Manual Approval') {
            steps {
                input message: 'Pre-check passed. Do you want to proceed with the software installation?'
            }
        }

        // stage('Copy code to infra-deploy') {
        //     steps {
        //         withCredentials([string(credentialsId: 'github_token', variable: 'GITHUB_TOKEN')]) {
        //             sh '''
        //                 rm -rf infra-deploy
        //                 git clone https://github.com/FonsahPageo/infra-deploy.git
        //                 rm -rf configManagement/.git
        //                 cp -R configManagement/* infra-deploy/
        //                 rm -rf configManagement
        //                 cd infra-deploy
        //                 git config user.email "ashprincepageo@gmail.com"
        //                 git config user.name "FonsahPageo"
        //                 git add .
        //                 git commit -m "Infrastructure-Deploy"
        //                 git push https://FonsahPageo:$GITHUB_TOKEN@github.com/FonsahPageo/infra-deploy.git
        //             '''
        //         }
        //     }
        // }

        // Uncomment and modify as necessary for actual installation
        stage('Install Software') {
            steps {
                script {
                    sh '''
                    ansible-playbook -i /var/jenkins_home/ansible/inventory/hosts.ini \
                    /var/jenkins_home/ansible/playbooks/install_tools.yaml --become --diff \
                    --private-key ${PRIVATE_KEY_PATH}
                    '''
                }
            }
        }
    }
}
